# Generated by Django 4.2.20 on 2025-04-01 13:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0009_billing_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing_address',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billing_address',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
