# Generated by Django 4.2.20 on 2025-04-02 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0011_order_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='product_name',
            new_name='product',
        ),
    ]
