# Generated by Django 4.2.20 on 2025-04-02 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0012_rename_product_name_orderitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_image',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
