# Generated by Django 4.2.20 on 2025-05-14 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("eshop", "0014_productorder"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productorder",
            old_name="product_order",
            new_name="buyer",
        ),
        migrations.RenameField(
            model_name="productorder",
            old_name="productorder",
            new_name="product",
        ),
    ]
