# Generated by Django 4.2.20 on 2025-05-14 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eshop", "0015_rename_product_order_productorder_buyer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productorder",
            name="address",
            field=models.CharField(default=1, max_length=225),
            preserve_default=False,
        ),
    ]
